lab0 try
Datrooo/OOP_FIT pull request #5
Opened 2024-09-25 05:29 UTC by Datrooo

2024-09-25 18:49 UTC, danillo19 requested changes
Вообще хорошо написано, но на классы надо норм декомпозировать и не смешивать зоны ответсвенности классов, раздели на 2 класса чтение и подсчет и аппрувну

2024-09-25 18:49 UTC, danillo19 commented on lab0b/readNcount.h
> +};
Классы должны быть как можно меньше, т.е выполнять что-то одно, например только чтение, только запись, только подсчет и тд

2024-09-25 18:49 UTC, danillo19 commented on lab0b/writer.cpp
> +    std::vector<std::pair<std::string, int>> listToSort(wordFrequency.begin(), wordFrequency.end());
у тебя переменная называется listToSort, а тип вектор, если уже пишешь list, то хотя бы listOfWordsToSort

2024-09-25 18:49 UTC, danillo19 commented on lab0b/writer.cpp
> +    std::sort(listToSort.begin(), listToSort.end(), [](auto& a, auto& b){return a.second > b.second;});
в лабе надо сортировать не только по частоте, но еще и по алфавиту, если частота совпадает

2024-09-25 18:49 UTC, danillo19 commented on lab0b/writer.h
> +#define PROCENT 100
правильно будет percent

2024-09-25 18:49 UTC, danillo19 commented on lab0b/readNcount.cpp
> +        if (isalnum(ch)) {fixed += std::tolower(ch);}
лучше писать так, такие однострочники тяжко читать, когда много кода, лучше так:
```
if (isalnum(ch)) {
    fixed += std::tolower(ch);
}
```

2024-09-25 18:49 UTC, danillo19 commented on lab0b/main.cpp
> +    }
лучше разделять пустой строкой различные блоки кода

2024-09-25 18:49 UTC, danillo19 commented on lab0b/main.cpp
> +    fout.close();
вообще лучше писать так, чтобы лишних ресурсов не затрачивать по возможности, здесь ты открываешь сразу выходной файл. Что если не получится че то считать с input файла, поэтому логику лучше разделить на 3 части:
Считывание
Подсчет
Сохранение в csv

2024-09-26 06:07 UTC, Datrooo commented on lab0b/writer.cpp
> +    std::sort(listToSort.begin(), listToSort.end(), [](auto& a, auto& b){return a.second > b.second;});
Из-за того что я копирую в listOfWordsToSort из map, а эта структура данных автоматически сортирует по ключу , и при этом знак в функции строгий, то в результате сортировка и по алфавиту, и по частоте

2024-09-27 03:56 UTC, danillo19 approved these changes

2024-09-27 03:56 UTC, danillo19 commented on lab0b/counter.cpp
> +int Counter::getCntWords(){
че такое Cnt? Зачем сокращать?

2024-09-27 03:56 UTC, danillo19 commented on lab0b/app.h
> +        std::ofstream fout{nullptr};
лучше вынести эти стримы в reader и writer соответственно

2024-09-27 03:56 UTC, danillo19 commented on lab0b/app.cpp
> +}
почему App отвечает за работу со стримами? Кажется App должен выполянять сам алгоритм, стримы это ответственность других классов

2024-09-27 03:56 UTC, danillo19 commented on lab0b/app.cpp
> +    App::closeStreams();
In стрим можно закрыть и до writeCsv

2024-09-27 03:56 UTC, danillo19 commented on lab0b/app.cpp
> +    if (!App::openInputFile(fileIn)){
тоже перенести openInput в Reader, а openOutput во writer

2024-09-27 03:56 UTC, danillo19 commented on lab0b/writer.cpp
> +    std::sort(listOfWordsToSort.begin(), listOfWordsToSort.end(), [](auto& a, auto& b){return a.second > b.second;});
в лабе надо сортировать не только по частоте, но и по алфавиту, если частота совпадает

2024-09-29 19:57 UTC, danillo19 approved these changes

2025-02-20 08:00 UTC, merged